services:
  airsonic-advanced:
    container_name: airsonic-advanced
    image: airsonicadvanced/airsonic-advanced:latest
    restart: unless-stopped
    ports: 
      - 4040:4040
      - 4041:4041 #UPnp
    # user: pid:gid #optional - run container as user
    environment:
      TZ: America/New_York #optional - show logs in local timezone
      JAVA_OPTS: '-Dserver.forward-headers-strategy=native' #optional - if you use a reverse-proxy
    volumes:
      - ./data:/var/airsonic
      - ./data:/data # gonic db etc
      - ./music:/music:ro # your music
      - ./podcasts:/podcasts # your podcasts
      - ./playlists:/playlists # your playlists
      - ./cache:/cache # transcode / covers / etc cache dir
    privileged: true
      
