// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// i2s_pio //
// ------- //

#define i2s_pio_wrap_target 0
#define i2s_pio_wrap 7
#define i2s_pio_pio_version 0

static const uint16_t i2s_pio_program_instructions[] = {
            //     .wrap_target
    0x6001, //  0: out    pins, 1         side 0
    0x1040, //  1: jmp    x--, 0          side 2
    0x6801, //  2: out    pins, 1         side 1
    0xb842, //  3: nop                    side 3
    0x6801, //  4: out    pins, 1         side 1
    0x1884, //  5: jmp    y--, 4          side 3
    0x6001, //  6: out    pins, 1         side 0
    0xb042, //  7: nop                    side 2
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2s_pio_program = {
    .instructions = i2s_pio_program_instructions,
    .length = 8,
    .origin = -1,
    .pio_version = i2s_pio_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config i2s_pio_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2s_pio_wrap_target, offset + i2s_pio_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

